---
title: "Covid19"
author: "Miguel Rodrigues (miguel.b.rodrigues@gmail.com)"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 10pt

output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    fig_width: 6
    fig_height: 3.5
    theme: readable
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
```

```{r message=FALSE, warning=FALSE, results = FALSE}
#
# import
library(ggplot2)
library(reshape2)
library(dplyr)
library(plotly)
library(viridis)
library(knitr)

ecdc_flist <-list.files(path = "./")
Link <- c()
Data <- c()
presentation <- c()
ignore <- 0
for (i in 1:length(ecdc_flist)){
  x <- ecdc_flist[i]
  if ( substr(x, nchar(x) - 15 + 1 , nchar(x)-11) == "2020" ) {
    Link[i] <- ecdc_flist[i]
    Data[i] <- substr(ecdc_flist[i], start=1,stop =80)
    presentation[length(ecdc_flist)+1-i - ignore] <-  sprintf ("[%s](%s)", Data[i], Link[i])
  } else {
    ignore <- ignore + 1
  }
}

```


### AESE Presentation 2020 04 24
```{r  message=FALSE}
kable(  data.frame(presentation), row.names = FALSE)
```
